# apriltag:                           # namespace
#     apriltag:                       # node name
#         ros__parameters:
#             # required
image_transport: raw    # image format: "raw" or "compressed" (default: raw)
family: 36h11           # tag family name: 16h5, 25h9, 36h11 (default: 36h11)
size: 0.037             # tag edge size in meter (default: 2.0)
z_up: true              # rotate about x-axis to have Z pointing upwards (default: false)

# (optional) tuning of detection
max_hamming: 0          # maximum allowed hamming distance (corrected bits)
decimate: 1.0           # decimate resolution for quad detection
blur: 0.0               # sigma of Gaussian blur for quad detection
refine-edges: 1         # snap to strong gradients
threads: 1              # number of threads
debug: 0                # write additional debugging images to current working directory

# (optional) list of tags
tag_ids: [0]            # tag IDs for which to publish transform
tag_frames: [tag0]      # optional frame names
